/* Generated by Yosys 0.67+111 (git sha1 4821ed17b-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* top =  1  *)
(* src = "counter_4bit.v:1.1-13.10" *)
module counter_4bit(clk, rst, count);
  (* src = "counter_4bit.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "counter_4bit.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "counter_4bit.v:4.21-4.26" *)
  output [3:0] count;
  reg [3:0] count;
  wire _00_;
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4bit.v:11.22-11.31|C:\\tools\\OSS-CA~1\\bin\\../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4bit.v:11.22-11.31|C:\\tools\\OSS-CA~1\\bin\\../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _03_;
  assign _02_[0] = ~count[0];
  assign _00_ = count[0] & count[1];
  assign _01_ = ~(count[2] & _00_);
  assign _03_[2] = count[2] ^ _00_;
  assign _03_[3] = ~(count[3] ^ _01_);
  assign _03_[1] = count[0] ^ count[1];
  (* src = "counter_4bit.v:7.5-12.12" *)
  always @(posedge clk)
    if (rst) count[0] <= 1'h0;
    else count[0] <= _02_[0];
  (* src = "counter_4bit.v:7.5-12.12" *)
  always @(posedge clk)
    if (rst) count[1] <= 1'h0;
    else count[1] <= _03_[1];
  (* src = "counter_4bit.v:7.5-12.12" *)
  always @(posedge clk)
    if (rst) count[2] <= 1'h0;
    else count[2] <= _03_[2];
  (* src = "counter_4bit.v:7.5-12.12" *)
  always @(posedge clk)
    if (rst) count[3] <= 1'h0;
    else count[3] <= _03_[3];
  assign _02_[3:1] = count[3:1];
  assign _03_[0] = _02_[0];
endmodule
